// frontend/src/components/ProductList.vue
<template>
  <div>
    <h2>Product List</h2>
    <table>
      <thead>
        <tr>
          <th>SKU</th>
          <th>Name</th>
          <th>Price</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="product in products" :key="product.id">
          <td>{{ product.sku }}</td>
          <td>{{ product.name }}</td>
          <td>{{ product.price }}</td>
          <td>
            <button @click="emits('add-cart', product)">Add to Cart</button>
            <button @click="$emit('edit-product', product)">Edit</button>
            <button @click="$emit('delete-product', product.id)">Delete</button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script lang="ts" setup>
const props = defineProps({
  products: Array,
});
const emits = defineEmits(['edit-product', 'delete-product', 'add-cart']);
</script>

// frontend-react/src/components/productList.tsx
import React from 'react';

interface Product {
  id: string;
  sku: string;
  name: string;
  price: number;
}

interface ProductListProps {
  products: Product[];
  editProduct: (product: Product) => void;
  deleteProduct: (product: Product) => void;
  addCart: (product: Product) => void;
}

const ProductList: React.FC<ProductListProps> = ({ products, editProduct, deleteProduct, addCart }) => {
  return (
    <div className="product-list-container">
      <h2 className="product-list-title">Product List</h2>
      <table className="product-list-table">
        <thead>
          <tr>
            <th>SKU</th>
            <th>Name</th>
            <th>Price</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {products.map((product) => (
            <tr key={product.id}>
              <td>{product.sku}</td>
              <td>{product.name}</td>
              <td>${product.price.toFixed(2)}</td>
              <td>
                <button onClick={() => editProduct(product)} className="button edit-button">
                  Edit
                </button>
                <button onClick={() => addCart(product)} className="button add-to-cart-button">
                  Add to Cart
                </button>
                <button onClick={() => deleteProduct(product)} className="button delete-button">
                  Delete
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default ProductList;
