// frontend/src/components/ProductForm.vue
<template>
  <div>
    <h2>{{ form.editing ? 'Edit Product' : 'Add Product' }}</h2>
    <form @submit.prevent="handleSubmit">
      <input v-model="form.sku" placeholder="SKU" required />
      <input v-model="form.name" placeholder="Name" required />
      <input v-model.number="form.price" type="number" placeholder="Price" required />
      <button type="submit">{{ form.editing ? 'Update' : 'Add' }}</button>
      <button type="button" v-if="form.editing" @click="cancelEdit">Cancel</button>
    </form>
  </div>
</template>

<script lang="ts" setup>
import { reactive, watch } from 'vue';

const props = defineProps({
  editProduct: Object, // Product to edit
});

const emits = defineEmits(['save-product']); // Emit an event to save or update the product

const form = reactive({
  id: '',
  sku: '',
  name: '',
  price: null as number | null,
  editing: false,
});

// Watch for changes in `editProduct` to populate the form
watch(
  () => props.editProduct,
  (newProduct) => {
    if (newProduct) {
      form.id = newProduct.id;
      form.sku = newProduct.sku;
      form.name = newProduct.name;
      form.price = newProduct.price;
      form.editing = true;
    }
  },
  { immediate: true }
);

const handleSubmit = () => {
  emits('save-product', { ...form });
  resetForm();
};

const cancelEdit = () => {
  resetForm();
};

const resetForm = () => {
  form.id = '';
  form.sku = '';
  form.name = '';
  form.price = null;
  form.editing = false;
};
</script>

// frontend-react/src/components/productForm.tsx
import React, { useState, useEffect } from 'react';
import { Product } from '../types/product';

interface ProductFormProps {
  editProduct: Product | null;
  saveProduct: (product: Product) => void;
}

const ProductForm: React.FC<ProductFormProps> = ({ editProduct, saveProduct }) => {
  const [form, setForm] = useState<Product>({
    id: '',
    sku: '',
    name: '',
    price: 0
  });
  const [canEdit, setCanEdit] = useState<boolean>(false);

  useEffect(() => {
    if (editProduct) {
      setForm(editProduct);
      setCanEdit(true);
    } else {
      resetForm();
      setCanEdit(false);
    }
  }, [editProduct]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>): void => {
    const { name, value } = e.target;
    setForm((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>): void => {
    e.preventDefault();
    saveProduct(form);
    resetForm();
  };

  const resetForm = (): void => {
    setForm({ id: '', sku: '', name: '', price: 0,});
    setCanEdit(false);
  };

  return (
    <div className="product-form-container">
      <h2>{canEdit ? 'Edit Product' : 'Add Product'}</h2>
      <form onSubmit={handleSubmit}>
        <input
          name="sku"
          value={form.sku}
          onChange={handleChange}
          placeholder="SKU"
          required
          className="input-field"
        />
        <input
          name="name"
          value={form.name}
          onChange={handleChange}
          placeholder="Name"
          required
          className="input-field"
        />
        <input
          name="price"
          type="number"
          value={form.price}
          onChange={handleChange}
          placeholder="Price"
          required
          className="input-field"
        />
        <button type="submit" className="submit-button">
          {canEdit ? 'Update' : 'Add'}
        </button>
      </form>
    </div>
  );
};

export default ProductForm;
