// frontend/src/components/Product.vue
<template>
    <div>
      <ProductForm
        :edit-product="editProduct"
        @save-product="saveProduct"
      />
      <ProductList
        :products="products"
        @edit-product="editProductDetails"
        @delete-product="deleteProduct"
        @add-cart="addCart"
      />
      <CartTable
        :cart="cartList"
        @update-cart="updateCart"
        @remove-cart="removeItemFromCart"/>
    </div>
  </template>
  
  <script lang="ts" setup>
  import { ref, reactive, onMounted } from 'vue';
  import ProductForm from './ProductForm.vue';
  import ProductList from './ProductList.vue';
  import CartTable from './CartTable.vue';
  
  const products = ref([]);
  const editProduct = ref(null);
  const cartList = ref([]);
  
  const fetchProducts = async () => {
    const res = await fetch('http://localhost:3000/products');
    products.value = await res.json();
  };

  const fetchCart = async () => {
    const res = await fetch('http://localhost:3000/cart');
    cartList.value = await res.json();
  };

  const addCart = async (product) => {
    await fetch('http://localhost:3000/cart', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ productId: product.id, quantity: 1 }),
      });
    const res = await fetch('http://localhost:3000/cart');
    cartList.value = await res.json();
  };

  const updateCart = async (cart) => {
    await fetch('http://localhost:3000/cart', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ productId: cart.productId, quantity: cart.quantity }),
      });
    const res = await fetch('http://localhost:3000/cart');
    cartList.value = await res.json();
  };

  const removeItemFromCart = async (productId) => {
    await fetch(`http://localhost:3000/cart/${productId}`, {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
    })
    await fetchCart();
  }
  
  
  const saveProduct = async (product) => {
    try {
      await fetch('http://localhost:3000/products', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(product),
      });
      await fetchProducts();
      editProduct.value = null;
      await fetchCart();
    } catch (error) {
      console.error('Failed to save product:', error);
    }
  };
  
  const editProductDetails = (product) => {
    editProduct.value = product; // Pass product to the form
  };
  
  const deleteProduct = async (id) => {
    try {
      await fetch(`http://localhost:3000/products/${id}`, { method: 'DELETE' });
      await fetchProducts();
      await fetchCart();
    } catch (error) {
      console.error('Failed to delete product:', error);
    }
  };
  
  onMounted( async() => {
    await fetchCart();
    await fetchProducts();
  });
  </script>
  import type CartTableVue from './CartTable.vue';

// frontend-react/src/components/product.tsx
import React, { useState, useEffect } from 'react';
import ProductForm from './productForm';
import ProductList from './productList';
// import CartTable from './CartTable';

interface Product {
  id: string;
  name: string;
  price: number;
  sku: string;
}

interface CartItem {
  productId: string;
  quantity: number;
}

const Product: React.FC = () => {
//     console.log('Product component rendered');
//   const [products, setProducts] = useState<Product[]>([]);
//   const [editProduct, setEditProduct] = useState<Product | null>(null);
//   const [cartList, setCartList] = useState<CartItem[]>([]);

//   const apiUrl = 'http://localhost:3000';

//   const fetchProducts = async (): Promise<void> => {
//       const res = await fetch(`${apiUrl}/products`);
//       const data: Product[] = await res.json();
//       console.log("data!!!!!", data);
//       setProducts(data);
//   };

//   const fetchCart = async (): Promise<void> => {
//     try {
//       const res = await fetch(`${apiUrl}/cart`);
//       const data: CartItem[] = await res.json();
//       setCartList(data);
//     } catch (error) {
//       console.error('Failed to fetch cart:', error);
//     }
//   };

//   const addCart = async (product: Product): Promise<void> => {
//     try {
//       await fetch(`${apiUrl}/cart`, {
//         method: 'POST',
//         headers: { 'Content-Type': 'application/json' },
//         body: JSON.stringify({ productId: product.id, quantity: 1 }),
//       });
//       fetchCart();
//     } catch (error) {
//       console.error('Failed to add to cart:', error);
//     }
//   };

//   const updateCart = async (cart: CartItem): Promise<void> => {
//     try {
//       await fetch(`${apiUrl}/cart`, {
//         method: 'PUT',
//         headers: { 'Content-Type': 'application/json' },
//         body: JSON.stringify(cart),
//       });
//       fetchCart();
//     } catch (error) {
//       console.error('Failed to update cart:', error);
//     }
//   };

//   const removeItemFromCart = async (productId: number): Promise<void> => {
//     try {
//       await fetch(`${apiUrl}/cart/${productId}`, { method: 'DELETE' });
//       fetchCart();
//     } catch (error) {
//       console.error('Failed to remove item from cart:', error);
//     }
//   };

//   const saveProduct = async (product: Product): Promise<void> => {
//     console.log(product);
//     try {
//       await fetch(`${apiUrl}/products`, {
//         method: 'POST',
//         headers: { 'Content-Type': 'application/json' },
//         body: JSON.stringify(product),
//       });
//       fetchProducts();
//       setEditProduct(null);
//       fetchCart();
//     } catch (error) {
//       console.error('Failed to save product:', error);
//     }
//   };

//   const deleteProduct = async (product: Product): Promise<void> => {
//     try {
//       await fetch(`${apiUrl}/products/${product.id}`, { method: 'DELETE' });
//       fetchProducts();
//       fetchCart();
//     } catch (error) {
//       console.error('Failed to delete product:', error);
//     }
//   };

  useEffect(() => {
    console.log('useEffect called');
    // fetchProducts();
    // fetchCart();
  }, []);

  return (
    // <div className="app-container">
    //   <ProductForm editProduct={editProduct} saveProduct={saveProduct} />
    //   <div className="product-cart-container">
    //     <ProductList
    //       products={products}
    //       editProduct={setEditProduct}
    //       deleteProduct={deleteProduct}
    //       addCart={addCart}
    //     />
    //   </div>
    // </div>
    <div>
        hheeh
    </div>
  );
};

export default Product;
